version: '3.7'
services:
  web-javascript:
    restart: always
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - .:/usr/share/nginx/html
    environment:
      - NGINX_HOST=walawalavo.com
      - NGINX_PORT=8088
